/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "Add module": {                                  "en": "Add NPM module",                                  "de": "NPM-Modul hinzufügen",                            "ru": "Добавить NPM модуль",                             "pt": "Adicionar módulo",                                "nl": "Module toevoegen",                                "fr": "Ajouter un module",                               "it": "Aggiungi modulo",                                 "es": "Agregar módulo",                                  "pl": "Dodaj moduł",                                     "zh-cn": "添加模块"},
    "Additional npm modules:": {                     "en": "Additional npm modules",                          "de": "Zusätzliche NPM-Module",                          "ru": "Дополнительные NPM Модули",                       "pt": "Módulos npm adicionais",                          "nl": "Extra npm-modules",                               "fr": "Modules NPM supplémentaires",                     "it": "Ulteriori moduli npm",                            "es": "Módulos npm adicionales",                         "pl": "Dodatkowe moduły npm",                            "zh-cn": "额外的npm模块"},
    "Allow creation of foreign objects": {           "en": "Allow creation of foreign objects",               "de": "Erstellung von Fremd-Objekten zulassen",          "ru": "Разрешить создание объектов не в этом адаптере",  "pt": "Permitir a criação de objetos estranhos",         "nl": "Maken van vreemde objecten toestaan",             "fr": "Autoriser la création d'objets étrangers",        "it": "Consentire la creazione di oggetti estranei",     "es": "Permitir la creación de objetos extraños.",       "pl": "Zezwól na tworzenie obcych obiektów",             "zh-cn": "允许创建异物"},
    "Backups will not contain any projects or modules installed via the Palletmanager": {"en": "Backups will not contain any projects or modules installed via the Palletmanager!", "de": "Backups enthalten keine Projekte und auch keine Module die mit dem Palletenmanager installiert wurden!", "ru": "Резервные копии не будут содержать никаких проектов или модулей, установленных через Palletmanager!", "pt": "Os backups não conterão nenhum projeto ou módulo instalado por meio do Palletmanager!", "nl": "Back-ups bevatten geen projecten of modules die zijn geïnstalleerd via de Palletmanager!", "fr": "Les sauvegardes ne contiendront aucun projet ou module installé via le Palletmanager!", "it": "I backup non conterranno progetti o moduli installati tramite Palletmanager!", "es": "¡Las copias de seguridad no contendrán ningún proyecto o módulo instalado a través del Palletmanager!", "pl": "Kopie zapasowe nie będą zawierać żadnych projektów ani modułów zainstalowanych za pośrednictwem Palletmanager!", "zh-cn": "备份将不包含通过Palletmanager安装的任何项目或模块！"},
    "Convert values to string:": {                   "en": "Convert ioBroker values to string",               "de": "ioBroker-Werte in Zeichenkette konvertieren",     "ru": "Конвертировать значения из ioBroker в \"строку\"", "pt": "Converter valores de ioBroker em string",         "nl": "IoBroker-waarden converteren naar tekenreeks",    "fr": "Convertir les valeurs de ioBroker en chaîne",     "it": "Converti i valori di ioBroker in stringa",        "es": "Convierta los valores de ioBroker en una cadena", "pl": "Konwertuj wartości ioBroker na ciąg",             "zh-cn": "将ioBroker值转换为字符串"},
    "Divided by comma": {                            "en": "Divided by comma",                                "de": "Getrennt mit Komma",                              "ru": "Через запятую",                                   "pt": "Dividido por vírgula",                            "nl": "Verdeeld door een komma",                         "fr": "Divisé par une virgule",                          "it": "Diviso in virgola",                               "es": "Dividido por coma",                               "pl": "Podzielone przecinkiem",                          "zh-cn": "逗号分隔"},
    "Enable Projects Feature:": {                    "en": "Enable Projects Feature",                         "de": "Projektfunktion aktivieren",                      "ru": "Включить проекты",                                "pt": "Ativar recurso de projetos",                      "nl": "Projecten inschakelen",                           "fr": "Activer la fonctionnalité de projets",            "it": "Abilita funzionalità progetti",                   "es": "Habilitar característica de proyectos",           "pl": "Włącz funkcję projektów",                         "zh-cn": "启用项目功能"},
    "Leave blank to disable basic authentication": { "en": "Leave blank to disable basic authentication",     "de": "Leer lassen, um die Basic-Authentifizierung zu deaktivieren", "ru": "Оставить пустым, чтобы отключить аутентификацию", "pt": "Deixe em branco para desativar a autenticação básica", "nl": "Laat dit leeg om basisverificatie uit te schakelen", "fr": "Laissez vide pour désactiver l'authentification de base", "it": "Lascia vuoto per disabilitare l'autenticazione di base", "es": "Dejar en blanco para deshabilitar la autenticación básica", "pl": "Pozostaw puste, aby wyłączyć podstawowe uwierzytelnianie", "zh-cn": "留空以禁用基本身份验证"},
    "Max allocated RAM:": {                          "en": "Max allocated RAM",                               "de": "Maximal zugewiesener RAM",                        "ru": "Выделено RAM",                                    "pt": "RAM alocada máxima",                              "nl": "Max toegewezen RAM",                              "fr": "Max allouée RAM",                                 "it": "RAM allocata massima",                            "es": "RAM máxima asignada",                             "pl": "Maksymalna przydzielona pamięć RAM",              "zh-cn": "最大分配RAM"},
    "Module names": {                                "en": "NPM module names",                                "de": "NPM-Modulnamen",                                  "ru": "Имена модулей",                                   "pt": "Nomes de módulos",                                "nl": "Module namen",                                    "fr": "Noms de modules",                                 "it": "Nomi dei moduli",                                 "es": "Nombres de módulos",                              "pl": "Nazwy modułów",                                   "zh-cn": "模块名称"},
    "Password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Contraseña",                                      "pl": "Hasło",                                           "zh-cn": "密码"},
    "Safe mode": {                                   "en": "Safe mode",                                       "de": "Sicherheitsmodus",                                "ru": "Безопасный режим",                                "pt": "Modo de segurança",                               "nl": "Veilige modus",                                   "fr": "Mode sans échec",                                 "it": "Modalità sicura",                                 "es": "Modo seguro",                                     "pl": "Tryb bezpieczeństwa",                             "zh-cn": "安全模式"},
    "Update select dialog": {                        "en": "Update select dialog",                            "de": "Update Dialog um ID auszuwählen",                 "ru": "Обновить переменные в диалоге выбора объектов",   "pt": "Atualizar caixa de diálogo de seleção",           "nl": "Update select dialoogvenster",                    "fr": "Mettre à jour le dialogue",                       "it": "Aggiorna la finestra di selezione",               "es": "Actualizar diálogo de selección",                 "pl": "Zaktualizuj wybrane okno dialogowe",              "zh-cn": "更新选择对话框"},
    "Use palletmanager:": {                          "en": "Use palletmanager",                               "de": "Palletenmanager benutzen",                        "ru": "Использовать palletmanager",                      "pt": "Use palletmanager",                               "nl": "Gebruik palletmanager",                           "fr": "Utiliser Palletmanager",                          "it": "Usa palletmanager",                               "es": "Utilice palletmanager",                           "pl": "Użyj menedżera palet",                            "zh-cn": "使用托盘管理器"},
    "User": {                                        "en": "User",                                            "de": "Benutzer",                                        "ru": "Пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
    "Web server port:": {                            "en": "Web server port",                                 "de": "Webserver Port",                                  "ru": "Порт веб сервера",                                "pt": "Porta do servidor da Web",                        "nl": "Webserverpoort",                                  "fr": "Port du serveur Web",                             "it": "Porta del server Web",                            "es": "Puerto del servidor web",                         "pl": "Port serwera internetowego",                      "zh-cn": "Web服务器端口"},
    "http root directory:": {                        "en": "http root directory",                             "de": "http Stammpfad",                                  "ru": "http root directory",                             "pt": "diretório raiz http",                             "nl": "http root directory",                             "fr": "répertoire racine http",                          "it": "directory root http",                             "es": "directorio raíz http",                            "pl": "główny katalog http",                             "zh-cn": "http根目录"},
    "node-red settings": {                           "en": "node-red settings",                               "de": "node-red Einstellungen",                          "ru": "Настройки node-red",                              "pt": "configurações de nó vermelho",                    "nl": "node-red instellingen",                           "fr": "paramètres de node-red",                          "it": "impostazioni del node-red",                       "es": "configuración de node-red",                       "pl": "ustawienia node-red",                             "zh-cn": "node-red设置"},
    "node-red update select dialog": {               "en": "node-red update select dialog",                   "de": "node-red SelectID Dialog aktualisieren",          "ru": "Обновить переменные в диалоге node-red",          "pt": "caixa de diálogo de seleção de atualização do nó-vermelho", "nl": "update select dialoogvenster",                    "fr": "boîte de dialogue de sélection de mise à jour de noeud", "it": "finestra di dialogo di selezione aggiornamento node-red", "es": "diálogo de selección de actualización node-red",  "pl": "okno dialogowe aktualizacji uaktualnienia węzła", "zh-cn": "node-red update选择对话框"},
};